### ISSUE TITLE
Hi, I'm suffering from a noticeable degradation. I'm wondering if the face crop size need to be enlarged, for example, 20%? Have you ever done some experiments on this?

### ISSUE THREAD

**Issue by young169** [cutz-j/FDFtNet#1]

**Comment by 05Bang** [comment]
First of all thank you for asking a question about our work.

When you mention the face crop size, do you mean the preprocessing MTCNN part in the
preprocess_dataset.py ?
As for now, we only tried the experiment with the default crop size, and are working on a extended research with different crop sizes.

**Comment by 05Bang** [comment]
> _No description provided._

First of all thank you for asking a question about our work.

When you mention the face crop size, do you mean the preprocessing MTCNN part in the
preprocess_dataset.py ?
As for now, we only tried the experiment with the default crop size, and are working on a extended research with different crop sizes.
